sudo: true
language: ruby
rvm:
  - 2.2.4
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential ruby-dev freeglut3-dev libfreeimage-dev libgl1-mesa-dev libopenal-dev libpango1.0-dev libsdl-ttf2.0-dev libsndfile-dev libxinerama-dev
 - gem install bundler -v 1.12.3

